// Single source for the static brand mark: app/icon.svg, docs/favicon.svg and
// app/favicon.ico are all emitted from the geometry below, so the two SVGs stay
// byte-identical instead of being hand-synced.
//
//   node scripts/generate/brand-assets.mjs           # write
//   node scripts/generate/brand-assets.mjs --check   # verify, exit 1 on drift
//
// The interactive mark lives in components/ui/BrandMark.tsx and picks a smaller
// cut below 19px. Static assets are pinned to the standard cut with the counter
// at its full radius; a narrowed counter closes up and reads as a solid block.
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..")

const CANVAS = 96
const CORNER_RADIUS = 22
const COUNTER_CENTER = 48
const COUNTER_RADIUS = 27
const ICO_EDGE = 64

// Literal --fg from app/globals.css (light theme); a static asset cannot read a CSS variable.
const MARK_COLOR = "#1a1813"

const BLOCK_PATH =
  "M22 0H74A22 22 0 0 1 96 22V74A22 22 0 0 1 74 96H22A22 22 0 0 1 0 74V22A22 22 0 0 1 22 0Z"
const COUNTER_PATH = "M75 48a27 27 0 1 0-54 0a27 27 0 1 0 54 0"

const SVG = `<!-- Generated by scripts/generate/brand-assets.mjs. Do not edit; app/icon.svg and docs/favicon.svg must stay byte-identical. -->
<svg xmlns="http://www.w3.org/2000/svg" width="${CANVAS}" height="${CANVAS}" viewBox="0 0 ${CANVAS} ${CANVAS}" fill="none">
  <path fill="${MARK_COLOR}" fill-rule="evenodd" d="${BLOCK_PATH} ${COUNTER_PATH}" />
</svg>
`

function insideBlock(x, y) {
  if (x < 0 || y < 0 || x > CANVAS || y > CANVAS) {
    return false
  }
  // Clamp to the inset rect: inside the straight bands one delta is zero.
  const cornerX = Math.min(Math.max(x, CORNER_RADIUS), CANVAS - CORNER_RADIUS)
  const cornerY = Math.min(Math.max(y, CORNER_RADIUS), CANVAS - CORNER_RADIUS)
  return Math.hypot(x - cornerX, y - cornerY) <= CORNER_RADIUS
}

function insideCounter(x, y) {
  return Math.hypot(x - COUNTER_CENTER, y - COUNTER_CENTER) <= COUNTER_RADIUS
}

/** Analytic coverage of block-minus-counter, supersampled for antialiasing. */
function coverage(pixelX, pixelY, samples) {
  const scale = CANVAS / ICO_EDGE
  let hits = 0
  for (let row = 0; row < samples; row += 1) {
    const y = (pixelY + (row + 0.5) / samples) * scale
    for (let column = 0; column < samples; column += 1) {
      const x = (pixelX + (column + 0.5) / samples) * scale
      if (insideBlock(x, y) && !insideCounter(x, y)) {
        hits += 1
      }
    }
  }
  return hits / (samples * samples)
}

/** 64x64 single-image ICO carrying a 32-bit BGRA DIB, as app/favicon.test.ts expects. */
function renderIco() {
  const red = Number.parseInt(MARK_COLOR.slice(1, 3), 16)
  const green = Number.parseInt(MARK_COLOR.slice(3, 5), 16)
  const blue = Number.parseInt(MARK_COLOR.slice(5, 7), 16)

  const pixels = Buffer.alloc(ICO_EDGE * ICO_EDGE * 4)
  for (let y = 0; y < ICO_EDGE; y += 1) {
    // DIB rows run bottom-up.
    const target = ICO_EDGE - 1 - y
    for (let x = 0; x < ICO_EDGE; x += 1) {
      const offset = (target * ICO_EDGE + x) * 4
      pixels[offset] = blue
      pixels[offset + 1] = green
      pixels[offset + 2] = red
      pixels[offset + 3] = Math.round(coverage(x, y, 8) * 255)
    }
  }

  const header = Buffer.alloc(40)
  header.writeUInt32LE(40, 0)
  header.writeInt32LE(ICO_EDGE, 4)
  header.writeInt32LE(ICO_EDGE * 2, 8) // XOR + AND heights.
  header.writeUInt16LE(1, 12)
  header.writeUInt16LE(32, 14)
  header.writeUInt32LE(pixels.length, 20)

  const mask = Buffer.alloc((ICO_EDGE / 8) * ICO_EDGE)
  const image = Buffer.concat([header, pixels, mask])

  const directory = Buffer.alloc(22)
  directory.writeUInt16LE(0, 0)
  directory.writeUInt16LE(1, 2)
  directory.writeUInt16LE(1, 4)
  directory.writeUInt8(ICO_EDGE, 6)
  directory.writeUInt8(ICO_EDGE, 7)
  directory.writeUInt16LE(1, 10)
  directory.writeUInt16LE(32, 12)
  directory.writeUInt32LE(image.length, 14)
  directory.writeUInt32LE(directory.length, 18)

  return Buffer.concat([directory, image])
}

export function brandAssets() {
  const svg = Buffer.from(SVG, "utf8")
  return [
    { contents: svg, file: "app/icon.svg" },
    { contents: svg, file: "docs/favicon.svg" },
    { contents: renderIco(), file: "app/favicon.ico" },
  ]
}

function main() {
  const check = process.argv.includes("--check")
  const stale = []

  for (const asset of brandAssets()) {
    const target = path.join(root, asset.file)
    const current = fs.existsSync(target) ? fs.readFileSync(target) : null
    if (current && current.equals(asset.contents)) {
      continue
    }
    if (check) {
      stale.push(asset.file)
      continue
    }
    fs.writeFileSync(target, asset.contents)
    process.stdout.write(`wrote ${asset.file}\n`)
  }

  if (stale.length > 0) {
    process.stderr.write(
      `Brand assets are out of date: ${stale.join(", ")}\nRun: npm run generate:brand-assets\n`,
    )
    process.exitCode = 1
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main()
}
