// Single source for the country flags shown in the app: one sprite with a <symbol> per
// catalog country, referenced as <use href="/flags.svg#xx">. The flags stay out of the
// JavaScript bundle and are fetched once as a separately cached static asset.
//
//   node scripts/generate/flag-sprite.mjs           # write
//   node scripts/generate/flag-sprite.mjs --check   # verify, exit 1 on drift
//
// Countries come from the same source file as the SERP country catalog, so the sprite and
// the catalog can never drift: every country the app can name has a symbol here.
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..")
const COUNTRIES = path.join(root, "scripts/generate/sources/markets/countries.json")
const FLAGS = path.join(root, "node_modules/country-flag-icons/3x2")
const SPRITE = "public/flags.svg"
const CODES = "lib/ui/generated/flag-sprite-codes.ts"

function countryCodes() {
  const countries = JSON.parse(fs.readFileSync(COUNTRIES, "utf8"))
  return [...new Set(countries.map((country) => country.countryCode))].sort()
}

/** One <symbol>: the source viewBox travels with it, because the set is not one aspect ratio. */
function symbolFor(code) {
  const file = path.join(FLAGS, `${code}.svg`)
  if (!fs.existsSync(file)) {
    return { code, missing: true }
  }
  const source = fs.readFileSync(file, "utf8").trim()
  const match = source.match(/^<svg\b[^>]*\bviewBox="([^"]+)"[^>]*>([\s\S]*)<\/svg>$/)
  if (!match) {
    return { code, unreadable: true }
  }
  return { code, markup: `<symbol id="${code.toLowerCase()}" viewBox="${match[1]}">${match[2]}</symbol>` }
}

/** The sprite plus the code list the renderer checks, so a symbol and its guard ship together. */
export function flagSpriteAssets() {
  const symbols = countryCodes().map(symbolFor)
  const broken = symbols.filter((symbol) => symbol.missing || symbol.unreadable)
  if (broken.length > 0) {
    throw new Error(
      `No usable flag for: ${broken.map((symbol) => symbol.code).join(", ")}. ` +
        "Add a fallback or drop the country from the catalog source.",
    )
  }
  const codes = symbols.map((symbol) => symbol.code)
  const body = symbols.map((symbol) => symbol.markup).join("\n")
  return [
    {
      contents: Buffer.from(
        `<!-- Generated by scripts/generate/flag-sprite.mjs. Do not edit. -->\n` +
          `<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" style="display:none">\n${body}\n</svg>\n`,
      ),
      file: SPRITE,
    },
    {
      contents: Buffer.from(
        `/*\n * Generated by scripts/generate/flag-sprite.mjs.\n * Do not edit manually. Regenerate with: npm run generate:flag-sprite\n */\n\n` +
          `/** ISO alpha-2 codes with a symbol in public/flags.svg, upper case. */\n` +
          `// biome-ignore format: Keep the generated code list on one line, like the country catalog.\n` +
          `export const FLAG_SPRITE_CODES: ReadonlySet<string> = new Set("${codes.join(" ")}".split(" "));\n`,
      ),
      file: CODES,
    },
  ]
}

function main() {
  const check = process.argv.includes("--check")
  const stale = []

  for (const asset of flagSpriteAssets()) {
    const target = path.join(root, asset.file)
    const current = fs.existsSync(target) ? fs.readFileSync(target) : null
    if (current?.equals(asset.contents)) {
      continue
    }
    if (check) {
      stale.push(asset.file)
      continue
    }
    fs.mkdirSync(path.dirname(target), { recursive: true })
    fs.writeFileSync(target, asset.contents)
    process.stdout.write(`wrote ${asset.file}\n`)
  }

  if (stale.length > 0) {
    process.stderr.write(
      `Flag sprite assets are out of date: ${stale.join(", ")}\nRun: npm run generate:flag-sprite\n`,
    )
    process.exitCode = 1
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main()
}
