// Sandbox-safe constants shared by Temporal workflows, activities, and provider code.
export const QUEUED_PERSISTENCE_LEASE_MS = 3 * 60_000;
export const QUEUED_RESULT_GET_TIMEOUT_MS = 45_000;
export const QUEUED_RESULT_DB_MAX_WAIT_MS = 10_000;
export const QUEUED_RESULT_DB_TRANSACTION_TIMEOUT_MS = 30_000;
export const QUEUED_RESULT_RELEASE_DB_MAX_WAIT_MS = 5_000;
export const QUEUED_RESULT_RELEASE_DB_TRANSACTION_TIMEOUT_MS = 5_000;
export const QUEUED_RESULT_PROCESSING_ALLOWANCE_MS = 15_000;
export const QUEUED_RESULT_ATTEMPT_BUDGET_MS =
  QUEUED_RESULT_GET_TIMEOUT_MS +
  QUEUED_RESULT_DB_MAX_WAIT_MS +
  QUEUED_RESULT_DB_TRANSACTION_TIMEOUT_MS +
  QUEUED_RESULT_PROCESSING_ALLOWANCE_MS;
export const QUEUED_RESULT_ACTIVITY_START_TO_CLOSE_MS = 2 * 60_000;
export const QUEUED_RESULT_ACTIVITY_HEARTBEAT_TIMEOUT_MS = 15_000;
export const QUEUED_RESULT_COMPLETE_OWNERSHIP_BUDGET_MS = Math.max(
  QUEUED_RESULT_DB_MAX_WAIT_MS +
    QUEUED_RESULT_DB_TRANSACTION_TIMEOUT_MS +
    QUEUED_RESULT_ATTEMPT_BUDGET_MS +
    QUEUED_RESULT_RELEASE_DB_MAX_WAIT_MS +
    QUEUED_RESULT_RELEASE_DB_TRANSACTION_TIMEOUT_MS,
  QUEUED_RESULT_ACTIVITY_START_TO_CLOSE_MS +
    QUEUED_RESULT_ACTIVITY_HEARTBEAT_TIMEOUT_MS +
    QUEUED_RESULT_RELEASE_DB_MAX_WAIT_MS +
    QUEUED_RESULT_RELEASE_DB_TRANSACTION_TIMEOUT_MS,
);
export const QUEUED_RESULT_LEASE_SAFETY_MARGIN_MS =
  QUEUED_PERSISTENCE_LEASE_MS - QUEUED_RESULT_COMPLETE_OWNERSHIP_BUDGET_MS;

export const QUEUED_RESULT_ACTIVITY_START_TO_CLOSE = "2 minutes";
export const QUEUED_RESULT_ACTIVITY_HEARTBEAT_TIMEOUT = "15 seconds";
export const QUEUED_RESULT_ACTIVITY_HEARTBEAT_MS = 5_000;
export const QUEUED_INSPECTION_ACTIVITY_START_TO_CLOSE = "1 minute";
export const QUEUED_INSPECTION_ACTIVITY_HEARTBEAT_TIMEOUT = "15 seconds";
export const QUEUED_INSPECTION_ACTIVITY_HEARTBEAT_MS = 5_000;

export const QUEUED_DEADLINE_DB_MAX_WAIT_MS = 10_000;
export const QUEUED_DEADLINE_DB_TRANSACTION_TIMEOUT_MS = 45_000;
export const QUEUED_DEADLINE_REASON =
  "Queued rank-check tasks exceeded the configured maximum queue age.";
export const QUEUED_INSPECTION_CANCELLATION_REASON =
  "Queued rank-check readiness inspection was cancelled.";
