import { describe, expect, it } from "vitest";
import {
  QUEUED_PERSISTENCE_LEASE_MS,
  QUEUED_RESULT_ACTIVITY_HEARTBEAT_TIMEOUT_MS,
  QUEUED_RESULT_ACTIVITY_START_TO_CLOSE_MS,
  QUEUED_RESULT_ATTEMPT_BUDGET_MS,
  QUEUED_RESULT_COMPLETE_OWNERSHIP_BUDGET_MS,
  QUEUED_RESULT_DB_MAX_WAIT_MS,
  QUEUED_RESULT_DB_TRANSACTION_TIMEOUT_MS,
  QUEUED_RESULT_GET_TIMEOUT_MS,
  QUEUED_RESULT_LEASE_SAFETY_MARGIN_MS,
  QUEUED_RESULT_PROCESSING_ALLOWANCE_MS,
  QUEUED_RESULT_RELEASE_DB_MAX_WAIT_MS,
  QUEUED_RESULT_RELEASE_DB_TRANSACTION_TIMEOUT_MS,
} from "./queued-timeouts";

describe("queued result timeout budget", () => {
  it("keeps the complete owning attempt strictly below lease expiry", () => {
    expect(QUEUED_RESULT_ATTEMPT_BUDGET_MS).toBe(
      QUEUED_RESULT_GET_TIMEOUT_MS +
        QUEUED_RESULT_DB_MAX_WAIT_MS +
        QUEUED_RESULT_DB_TRANSACTION_TIMEOUT_MS +
        QUEUED_RESULT_PROCESSING_ALLOWANCE_MS,
    );
    expect(QUEUED_RESULT_COMPLETE_OWNERSHIP_BUDGET_MS).toBeLessThan(QUEUED_PERSISTENCE_LEASE_MS);
    expect(QUEUED_RESULT_COMPLETE_OWNERSHIP_BUDGET_MS).toBeGreaterThanOrEqual(
      QUEUED_RESULT_DB_MAX_WAIT_MS +
        QUEUED_RESULT_DB_TRANSACTION_TIMEOUT_MS +
        QUEUED_RESULT_ATTEMPT_BUDGET_MS +
        QUEUED_RESULT_RELEASE_DB_MAX_WAIT_MS +
        QUEUED_RESULT_RELEASE_DB_TRANSACTION_TIMEOUT_MS,
    );
    expect(QUEUED_RESULT_COMPLETE_OWNERSHIP_BUDGET_MS).toBeGreaterThanOrEqual(
      QUEUED_RESULT_ACTIVITY_START_TO_CLOSE_MS +
        QUEUED_RESULT_ACTIVITY_HEARTBEAT_TIMEOUT_MS +
        QUEUED_RESULT_RELEASE_DB_MAX_WAIT_MS +
        QUEUED_RESULT_RELEASE_DB_TRANSACTION_TIMEOUT_MS,
    );
    expect(QUEUED_RESULT_LEASE_SAFETY_MARGIN_MS).toBe(
      QUEUED_PERSISTENCE_LEASE_MS - QUEUED_RESULT_COMPLETE_OWNERSHIP_BUDGET_MS,
    );
    expect(QUEUED_RESULT_LEASE_SAFETY_MARGIN_MS).toBeGreaterThanOrEqual(30_000);
  });
});
