import { downloadTrackingEvidence } from "@/lib/ai-tracking/exports/browser";
import type {
  TrackingSampleRow,
  TrackingWorkspaceData,
} from "@/lib/ai-tracking/projections/workspace";
import type { TrackingWorkspaceActions } from "./AiTrackingWorkspace";
import { generationFixtureActions } from "./generation-fixtures";
export const trackingWorkspaceFixture: TrackingWorkspaceData = {
  domain: "acme.dev",
  canWrite: true,
  topics: [
    {
      id: "ait_fixture",
      name: "Choosing a rank tracker",
      description: "Questions from independent teams",
      status: "active",
    },
    { id: "ait_competitors", name: "Comparisons", description: null, status: "active" },
  ],
  prompts: [
    {
      id: "aip_neutral",
      text: "Which rank trackers work well for a small team?",
      label: "Neutral",
      topicId: "ait_fixture",
      topicName: "Choosing a rank tracker",
      revisionId: "apr_neutral",
      revision: 2,
      sources: ["consumer_scrape", "google_aio"],
      lastResult: {
        sampleId: "asm_answer",
        revisionId: "apr_neutral_original",
        text: "Original exact historical prompt",
        measurement: "answer_present",
        observedAt: "2026-10-07T09:00:00.000Z",
        recordedAt: "2026-10-07T09:01:00.000Z",
      },
      nextRunAt: "2026-10-12T09:00:00.000Z",
      category: "neutral",
      status: "active",
    },
    {
      id: "aip_branded",
      text: "What are the strengths and limitations of Acme for rank tracking?",
      label: "Branded",
      topicId: "ait_fixture",
      topicName: "Choosing a rank tracker",
      revisionId: "apr_branded",
      revision: 1,
      sources: ["model_api"],
      sourceProvenance: "model_generated_hypothesis",
      lastResult: {
        sampleId: "asm_unknown",
        revisionId: "apr_branded",
        text: "What are the strengths and limitations of Acme for rank tracking?",
        measurement: "unknown",
        observedAt: null,
        recordedAt: "2026-10-08T09:00:00.000Z",
      },
      nextRunPending: true,
      category: "branded",
      status: "active",
    },
    {
      id: "aip_comparison",
      text: "How does Acme compare with Example for tracking search visibility?",
      label: "Comparative",
      topicId: "ait_competitors",
      topicName: "Comparisons",
      revisionId: "apr_comparison",
      revision: 3,
      sources: ["consumer_scrape", "model_api", "google_aio"],
      sourceScopeLimited: true,
      sourceProvenance: "provider_dataset",
      category: "comparative",
      status: "active",
    },
  ],
  runs: [
    { id: "air_oct08", state: "partial", createdAt: "2026-10-08T09:00:00.000Z", sampleCount: 3 },
    { id: "air_oct07", state: "completed", createdAt: "2026-10-07T09:00:00.000Z", sampleCount: 3 },
  ],
  schedules: [
    {
      id: "ais_weekly",
      name: "Weekly consumer check",
      cron: "0 9 * * 1",
      timezone: "Europe/Warsaw",
      enabled: false,
      promptIds: ["aip_neutral"],
      configurations: [
        {
          provider: "dataforseo",
          source: "consumer_scrape",
          engine: "chat_gpt",
          endpoint: "ai_optimization/chat_gpt/llm_scraper/task_post",
          model: null,
          parameters: { language_code: "pl", location_name: "Poland" },
        },
      ],
    },
  ],
};
export const trackingSampleFixtures: TrackingSampleRow[] = [
  {
    id: "asm_answer",
    measurement: "answer_present",
    source: "consumer_scrape",
    engine: "chat_gpt",
    prompt: trackingWorkspaceFixture.prompts[0].text,
    promptRevisionId: "apr_neutral",
    evidence: {
      answerText:
        "For a small team, consider Acme when you need a self-hosted tracker with your own data sources. Compare reporting needs, location support, and provider costs before choosing.",
      raw: null,
      answerTruncated: false,
      rawTruncated: false,
      searchResults: [],
      requestedLocale: "en-US",
      effectiveLocale: null,
      localeMechanism: "provider_location",
      requestedModel: null,
      actualModel: null,
      providerStatus: "20000",
      observedAt: "2026-10-08T09:01:02.000Z",
      fetchedAt: "2026-10-08T09:01:03.000Z",
      recordedSource: "fresh",
    },
    citations: [
      { url: "https://example.com/rank-tracking-guide", title: "Rank tracking guide", position: 1 },
    ],
    costUsd: "0.004",
    costState: "confirmed",
  },
  {
    id: "asm_absent",
    measurement: "aio_not_present",
    source: "google_aio",
    engine: "google",
    prompt: trackingWorkspaceFixture.prompts[1].text,
    promptRevisionId: "apr_branded",
    evidence: null,
    citations: [],
    costUsd: "0.0006",
    costState: "confirmed",
  },
  {
    id: "asm_unknown",
    measurement: "unknown",
    source: "model_api",
    engine: "chat_gpt",
    prompt: trackingWorkspaceFixture.prompts[2].text,
    promptRevisionId: "apr_comparison",
    evidence: null,
    citations: [],
    costUsd: null,
    costState: "unknown",
  },
];
export const trackingFixtureActions: TrackingWorkspaceActions = {
  generation: generationFixtureActions,
  save: async () => trackingWorkspaceFixture,
  preview: async (_promptIds, configurations) => ({
    configurations,
    credentialConnectionId: "fixture_connection",
    credentialVersion: "fixture_credential",
    budgetRevision: "fixture_budget",
    consentRevision: "fixture_consent",
    estimatedCostCents: 1.2,
  }),
  launch: async () => trackingWorkspaceFixture,
  samples: async () => ({ items: trackingSampleFixtures, nextCursor: null }),
  runs: async () => ({ items: [], nextCursor: null }),
  cancel: async () => trackingWorkspaceFixture,
  compare: async () => ({
    current: {
      expected: 3,
      observed: 3,
      eligible: 1,
      mentioned: 1,
      absentAio: 1,
      partial: 0,
      failed: 0,
      unknown: 1,
      missing: 0,
      coverage: 2 / 3,
      mentionRate: 1,
    },
    comparable: false,
    reason: "At least 90% complete coverage is required in both periods",
    delta: null,
    currentRunId: "air_oct08",
    nextCursor: null,
  }),
  export: async (runId, format, cursor) =>
    downloadTrackingEvidence(
      runId,
      format,
      async () => ({ items: trackingSampleFixtures, nextCursor: null }),
      cursor,
    ),
  suggest: async () => ({
    drafts: [],
    method: "manual_fallback",
    limitations: ["Add project context or enter prompts manually."],
  }),
};
