export const colorTokenNames = [
  "bg",
  "bg-elev",
  "bg-sidebar",
  "bg-sunken",
  "bg-inset",
  "fg",
  "fg-muted",
  "fg-faint",
  "border",
  "border-soft",
  "border-strong",
  "nav-active",
  "accent",
  "accent-hover",
  "accent-soft",
  "blue",
  "purple",
  "green",
  "red",
  "yellow",
  "yellow-strong",
  "yellow-text",
  "red-text",
  "rank-bucket-green",
  "rank-bucket-green-muted",
  "rank-bucket-yellow",
  "rank-bucket-orange",
  "rank-bucket-red",
  "code-bg",
  "code-fg",
  "code-faint",
  "code-border",
] as const;

export type ColorTokenName = (typeof colorTokenNames)[number];
export type ColorSchemeName = "light" | "dark";

export const colorSchemes = {
  light: {
    bg: "#F2EEE4",
    "bg-elev": "#FBF9F4",
    "bg-sidebar": "#FFFFFF",
    "bg-sunken": "#ECE7DB",
    "bg-inset": "#E2DDD0",
    fg: "#1A1813",
    "fg-muted": "#6B6657",
    "fg-faint": "#9A9588",
    border: "#E8E4D9",
    "border-soft": "#F0EEE6",
    "border-strong": "#D9D4C7",
    "nav-active": "#EDEAE1",
    accent: "#D97757",
    "accent-hover": "#C8643F",
    "accent-soft": "#F7E8E0",
    blue: "#4F86E8",
    purple: "#8E6FE0",
    green: "#3C9A63",
    red: "#C8463A",
    yellow: "#E0A93B",
    "yellow-strong": "#B07D10",
    "yellow-text": "#8A6516",
    "red-text": "#B03A2E",
    "rank-bucket-green": "#3C9A63",
    "rank-bucket-green-muted": "#7FB36B",
    "rank-bucket-yellow": "#E0A93B",
    "rank-bucket-orange": "#E08A4E",
    "rank-bucket-red": "#C8463A",
    "code-bg": "#1C1A16",
    "code-fg": "#EDEAE0",
    "code-faint": "#8C887C",
    "code-border": "#33302A",
  },
  dark: {
    bg: "#0F0C07",
    "bg-elev": "#1B1810",
    "bg-sidebar": "#070603",
    "bg-sunken": "#15110A",
    "bg-inset": "#080704",
    fg: "#ECE7DB",
    "fg-muted": "#9F998A",
    "fg-faint": "#6E685A",
    border: "#2E281D",
    "border-soft": "#221D15",
    "border-strong": "#423B2E",
    "nav-active": "#231F17",
    accent: "#E08A6A",
    "accent-hover": "#EC9A7C",
    "accent-soft": "#2A2018",
    blue: "#6A9BF0",
    purple: "#9E82E6",
    green: "#57A77E",
    red: "#E0705C",
    yellow: "#E6B452",
    "yellow-strong": "#EEC069",
    "yellow-text": "#EEC069",
    "red-text": "#E0705C",
    "rank-bucket-green": "#57A77E",
    "rank-bucket-green-muted": "#8CC07A",
    "rank-bucket-yellow": "#E6B452",
    "rank-bucket-orange": "#EC9A63",
    "rank-bucket-red": "#E0705C",
    "code-bg": "#0E0D0A",
    "code-fg": "#ECE7DB",
    "code-faint": "#7E7A6E",
    "code-border": "#26231E",
  },
} as const satisfies Record<ColorSchemeName, Record<ColorTokenName, `#${string}`>>;

export const tailwindTokenColors = Object.fromEntries(
  colorTokenNames.map((name) => [name, `var(--${name})`]),
) as Record<ColorTokenName, string>;
