export const MCP_TOOL_NAMES = [
  "get_health",
  "get_capabilities",
  "get_cloud_import_compatibility",
  "get_provider_rates",
  "get_cost_estimate",
  "get_me",
  "update_me",
  "list_projects",
  "create_project",
  "get_project",
  "search_locations",
  "update_project",
  "delete_project",
  "get_project_defaults",
  "update_project_defaults",
  "list_keywords",
  "list_ranked_keyword_suggestions",
  "research_keywords",
  "analyze_backlinks",
  "load_more_backlink_rows",
  "get_keyword_metrics",
  "add_keywords",
  "get_keyword",
  "update_keyword",
  "set_keyword_target_url",
  "delete_keyword",
  "bulk_update_keywords",
  "run_rank_check",
  "get_rank_history",
  "export_rank_history",
  "list_sitemap_monitors",
  "enable_sitemap_monitor",
  "disable_sitemap_monitor",
  "get_rank_check_result",
  "create_signal",
  "list_signals",
  "list_traffic_snapshots",
  "list_search_performance_query_stats",
  "sync_project_traffic",
  "list_api_keys",
  "create_api_key",
  "revoke_api_key",
  "list_project_api_keys",
  "create_project_api_key",
  "list_personal_tokens",
  "create_personal_token",
  "revoke_personal_token",
  "list_webhooks",
  "create_webhook",
  "update_webhook",
  "delete_webhook",
  "list_alert_rules",
  "create_alert_rule",
  "update_alert_rule",
  "delete_alert_rule",
  "list_triggered_alerts",
  "mute_triggered_alert",
  "mark_project_alerts_read",
  "list_team_members",
  "list_team_invites",
  "create_team_invite",
  "revoke_team_invite",
  "resend_team_invite",
  "update_team_member_role",
  "remove_team_member",
  "list_providers",
  "connect_provider",
  "test_provider_connection",
  "update_provider_settings",
  "set_provider_enabled",
  "set_provider_priority",
  "set_primary_provider",
  "disconnect_provider",
  "list_saved_views",
  "create_saved_view",
  "delete_saved_view",
  "list_competitors",
  "add_competitor",
  "remove_competitor",
  "get_notification_preferences",
  "update_notification_preferences",
  "list_migration_tokens",
  "mint_migration_token",
  "revoke_migration_token",
] as const;

export type McpToolName = (typeof MCP_TOOL_NAMES)[number];

const canonicalNames = new Set<string>(MCP_TOOL_NAMES);
const internalNameOverrides: Record<string, string> = {
  get_keyword_metrics: "get_keyword_metrics",
  research_keywords: "research_keywords",
};

export function internalMcpToolName(name: string) {
  if (!canonicalNames.has(name)) {
    throw new Error(`Unknown MCP tool: ${name}`);
  }
  return (
    internalNameOverrides[name] ??
    name.replace(/_([a-z0-9])/g, (_, letter: string) => letter.toUpperCase())
  );
}
