import type { JsonObject, McpToolDefinition } from "./definitions";

type ToolFactory = (name: string, fallback: JsonObject) => McpToolDefinition;

export function buildMcpToolDefinitions(
  tool: ToolFactory,
  schemas: Record<string, JsonObject>,
): McpToolDefinition[] {
  return [
    tool("getHealth", schemas.empty),
    tool("getCapabilities", schemas.empty),
    tool("getMe", schemas.empty),
    tool("updateMe", schemas.updateMe),
    tool("listProjects", schemas.empty),
    tool("createProject", schemas.createProject),
    tool("getProject", schemas.getProject),
    tool("searchLocations", schemas.searchLocations),
    tool("updateProjectDefaults", schemas.projectDefaults),
    tool("listKeywords", schemas.listKeywords),
    tool("listRankedKeywordSuggestions", schemas.listRankedKeywordSuggestions),
    tool("research_keywords", schemas.researchKeywords),
    tool("get_keyword_metrics", schemas.getKeywordMetrics),
    tool("listTrafficSnapshots", schemas.listTrafficSnapshots),
    tool("listSearchPerformanceQueryStats", schemas.listSearchPerformanceQueryStats),
    tool("syncProjectTraffic", schemas.syncProjectTraffic),
    tool("addKeywords", schemas.addKeywords),
    tool("getKeyword", schemas.getKeyword),
    tool("updateKeyword", schemas.updateKeyword),
    tool("setKeywordTargetUrl", schemas.updateKeyword),
    tool("deleteKeyword", schemas.getKeyword),
    tool("bulkUpdateKeywords", schemas.bulkUpdateKeywords),
    tool("runRankCheck", schemas.runRankCheck),
    tool("listRankChecks", schemas.rankChecks),
    tool("getRankHistory", schemas.rankChecks),
    tool("getRankCheckResult", schemas.getRankCheckResult),
    tool("listApiKeys", schemas.listApiKeys),
    tool("createApiKey", schemas.createApiKey),
    tool("revokeApiKey", schemas.revokeApiKey),
    tool("listPersonalTokens", schemas.empty),
    tool("createPersonalToken", schemas.createPersonalToken),
    tool("revokePersonalToken", schemas.revokePersonalToken),
    tool("listWebhooks", schemas.listProjectResources),
    tool("createWebhook", schemas.createWebhook),
    tool("updateWebhook", schemas.updateWebhook),
    tool("deleteWebhook", schemas.webhookMember),
    tool("listAlertRules", schemas.listProjectResources),
    tool("createAlertRule", schemas.createAlertRule),
    tool("updateAlertRule", schemas.updateAlertRule),
    tool("deleteAlertRule", schemas.deleteByRule),
    tool("listTriggeredAlerts", schemas.listProjectResources),
    tool("markProjectAlertsRead", schemas.markProjectAlertsRead),
    tool("muteTriggeredAlert", schemas.muteTriggeredAlert),
    tool("exportRankHistory", schemas.exportRankHistory),
    tool("listSitemapMonitors", schemas.listSitemapMonitors),
    tool("enableSitemapMonitor", schemas.updateSitemapMonitor),
    tool("disableSitemapMonitor", schemas.updateSitemapMonitor),
    tool("listTeamMembers", schemas.listProjectResources),
    tool("listTeamInvites", schemas.listProjectResources),
    tool("createTeamInvite", schemas.createProjectMember),
    tool("revokeTeamInvite", schemas.deleteByInvite),
    tool("resendTeamInvite", schemas.resendTeamInvite),
    tool("updateTeamMemberRole", schemas.updateTeamMemberRole),
    tool("removeTeamMember", schemas.removeTeamMember),
    tool("listProviders", schemas.listProjectResources),
    tool("connectProvider", schemas.providerSettings),
    tool("testProviderConnection", schemas.providerSettings),
    tool("updateProviderSettings", schemas.providerSettings),
    tool("disconnectProvider", schemas.provider),
    tool("listSavedViews", schemas.listSavedViews),
    tool("createSavedView", schemas.createSavedView),
    tool("deleteSavedView", schemas.deleteByView),
    tool("listCompetitors", schemas.listProjectResources),
    tool("addCompetitor", schemas.createProjectMember),
    tool("removeCompetitor", schemas.deleteByCompetitor),
    tool("getNotificationPreferences", schemas.getNotificationPreferences),
    tool("updateNotificationPreferences", schemas.createProjectMember),
    tool("listMigrationTokens", schemas.listProjectResources),
    tool("mintMigrationToken", schemas.createProjectMember),
    tool("revokeMigrationToken", schemas.deleteByToken),
  ];
}
