import type { BacklinksHistoryMonth, BacklinksRow, BacklinksSnapshot } from "@/lib/backlinks/types";

const monthValues = [
  ["2025-07", 23, 8, 3, 1],
  ["2025-08", 20, 7, 2, 1],
  ["2025-09", 26, 10, 3, 2],
  ["2025-10", 31, 8, 4, 1],
  ["2025-11", 28, 12, 2, 1],
  ["2025-12", 35, 9, 4, 2],
  ["2026-01", 30, 11, 3, 1],
  ["2026-02", 27, 8, 2, 1],
  ["2026-03", 36, 10, 4, 2],
  ["2026-04", 41, 14, 3, 1],
  ["2026-05", 32, 9, 2, 1],
  ["2026-06", 46, 12, 3, 1],
] as const;

const backlinksHistoryFixture: BacklinksHistoryMonth[] = monthValues.map(
  ([month, newLinks, lostLinks, newReferringDomains, lostReferringDomains]) => ({
    lostLinks,
    lostReferringDomains,
    month,
    newLinks,
    newReferringDomains,
  }),
);

function fixtureRow(overrides: Partial<BacklinksRow>): BacklinksRow {
  return {
    anchor: "acme-store.com",
    domainAuthority: 40,
    firstSeen: "2026-01-21",
    flags: [],
    linksCount: 1,
    lostAt: null,
    sourceDomain: "example.com",
    sourceUrl: "https://example.com/",
    spamScore: 2,
    status: "active",
    targetUrl: "https://acme-store.com/",
    ...overrides,
  };
}

const fixtureRows: BacklinksRow[] = [
  fixtureRow({
    domainAuthority: 91,
    firstSeen: "2026-07-20",
    flags: ["nofollow", "ugc"],
    linksCount: 3,
    sourceDomain: "reddit.com",
    sourceUrl: "https://reddit.com/r/standingdesks/comments/acme",
    status: "new",
    targetUrl: "https://acme-store.com/desks",
  }),
  fixtureRow({
    anchor: "Acme standing desk",
    domainAuthority: 91,
    flags: ["nofollow"],
    linksCount: 3,
    sourceDomain: "reddit.com",
    sourceUrl: "https://reddit.com/r/homeoffice/comments/acme",
  }),
  fixtureRow({
    anchor: "Acme Store",
    domainAuthority: 88,
    firstSeen: "2026-07-19",
    linksCount: 2,
    sourceDomain: "producthunt.com",
    sourceUrl: "https://producthunt.com/products/acme-store",
    status: "new",
  }),
  fixtureRow({
    anchor: "Acme ErgoPro 2 review",
    domainAuthority: 58,
    firstSeen: "2026-07-18",
    sourceDomain: "deskreview.io",
    sourceUrl: "https://deskreview.io/best-standing-desks-2026",
    status: "new",
    targetUrl: "https://acme-store.com/desks/ergopro-2",
  }),
  fixtureRow({
    anchor: "",
    domainAuthority: 58,
    firstSeen: "2026-04-02",
    flags: ["image"],
    sourceDomain: "deskreview.io",
    sourceUrl: "https://deskreview.io/guides/home-office-setup",
    targetUrl: "https://acme-store.com/desks/ergopro-2",
  }),
  fixtureRow({
    domainAuthority: 58,
    firstSeen: "2026-06-11",
    flags: ["nofollow"],
    sourceDomain: "deskreview.io",
    sourceUrl: "https://deskreview.io/newsletter/issue-84",
  }),
  fixtureRow({
    anchor: "Acme's minimalist desk line",
    domainAuthority: 52,
    firstSeen: "2025-11-08",
    lostAt: "2026-07-12",
    sourceDomain: "designweekly.co",
    sourceUrl: "https://designweekly.co/archive/minimalist-desks",
    status: "lost",
    targetUrl: "https://acme-store.com/collections/minimal",
  }),
  fixtureRow({
    anchor: "höhenverstellbarer Schreibtisch von Acme",
    domainAuthority: 46,
    firstSeen: "2026-04-30",
    sourceDomain: "homeofficehub.de",
    sourceUrl: "https://homeofficehub.de/ratgeber/schreibtisch",
    spamScore: 1,
    targetUrl: "https://acme-store.com/desks",
  }),
  ...Array.from({ length: 36 }, (_, index) =>
    fixtureRow({
      anchor: "Open website",
      domainAuthority: 41,
      firstSeen: "2026-06-23",
      flags: index === 0 ? ["sitewide"] : [],
      linksCount: index === 0 ? 3 : 1,
      sourceDomain: "toolindex.app",
      sourceUrl: `https://toolindex.app/${index === 0 ? "" : `${index}/`}product/acme-store`,
      spamScore: 6,
      targetUrl: "https://acme-store.com/?utm_source=toolindex",
    }),
  ),
  fixtureRow({
    anchor: "this desk from acme",
    domainAuthority: 33,
    firstSeen: "2026-02-17",
    flags: ["nofollow"],
    linksCount: 5,
    sourceDomain: "woodworkforum.net",
    sourceUrl: "https://woodworkforum.net/threads/acme-desk",
    spamScore: 4,
    targetUrl: "https://acme-store.com/desks",
  }),
];

export const backlinksSnapshotFixture: BacklinksSnapshot = {
  cached: true,
  cachedUntil: "2026-07-25T10:00:00.000Z",
  costCents: 0,
  fetchedAt: "2026-07-24T10:00:00.000Z",
  fetchedRowCount: 100,
  history: backlinksHistoryFixture,
  includeSubdomains: true,
  ok: true,
  provider: "dataforseo",
  rows: fixtureRows,
  summary: {
    backlinksTotal: 1685,
    brokenBacklinks: 0,
    brokenPages: 0,
    dofollowPct: 61,
    domainRank: 37,
    lostBacklinks: 999,
    lostReferringDomains: 99,
    newBacklinks: 999,
    newReferringDomains: 99,
    referringDomainsTotal: 48,
    referringPages: 1422,
    spamScore: 3,
  },
  target: "acme-store.com",
  targetScope: "site",
  totalRowsAvailable: 1685,
};
