// AUTO-GENERATED by scripts/deploy/bake-runtime-env.mjs at build time. Do not edit or commit.
import "server-only";

const BAKED: Record<string, string> = {};

// Read identity from the generated module, never from mutable runtime env.
export const getBakedAppRevision = () => "unknown";

// Fill only keys the runtime did not already provide, so platforms that DO
// inject env at request time take precedence over the build-time snapshot.
for (const [key, value] of Object.entries(BAKED)) {
  if (process.env[key] === undefined) {
    process.env[key] = value;
  }
}
