import { usageSettingsFeatureTestMessages } from "@/i18n/test-support/render-with-feature-messages";
import type { ProviderSpendConnection } from "@/lib/queries/provider-spend";

export const connections = [
  {
    allocation: { amountPerMonth: 1000, unit: "units" },
    allocationSource: "connection",
    billing: "quota",
    connectionId: "conn_serp",
    credentialSource: "own",
    enabled: true,
    features: [],
    primary: true,
    programmaticAllocation: { amountPerMonth: 1000, unit: "units" },
    projectedExhaustionAt: null,
    provider: "SerpApi",
    providerId: "serpapi",
    quotaReset: "billing_cycle",
    remaining: 0,
    requestCount: 28,
    unconfirmedCount: 0,
    state: "ok",
    status: "connected",
    own: {
      requestCount: 28,
      surfaces: {
        app: {
          allocation: { amountPerMonth: 1000, unit: "units" },
          projectedExhaustionAt: null,
          remaining: 0,
          state: "ok",
          used: 412,
          usedPercent: 41.2,
        },
        programmatic: {
          allocation: { amountPerMonth: 1000, unit: "units" },
          projectedExhaustionAt: null,
          remaining: 600,
          state: "ok",
          used: 400,
          usedPercent: 40,
        },
      },
      unconfirmedCount: 0,
      unit: "units",
      used: 412,
      usedPriorMonth: 1280,
    },
    credits: {
      requestCount: 0,
      surfaces: {
        app: {
          allocation: null,
          projectedExhaustionAt: null,
          remaining: null,
          state: "no_allocation",
          used: 0,
          usedPercent: null,
        },
        programmatic: {
          allocation: null,
          projectedExhaustionAt: null,
          remaining: null,
          state: "no_allocation",
          used: 0,
          usedPercent: null,
        },
      },
      unconfirmedCount: 0,
      unit: "cents",
      used: 0,
      usedPriorMonth: 0,
    },
    surfaces: {
      app: {
        allocation: { amountPerMonth: 1000, unit: "units" },
        projectedExhaustionAt: null,
        remaining: 0,
        state: "ok",
        used: 412,
        usedPercent: 41.2,
      },
      programmatic: {
        allocation: { amountPerMonth: 1000, unit: "units" },
        projectedExhaustionAt: null,
        remaining: 600,
        state: "ok",
        used: 400,
        usedPercent: 40,
      },
    },
    unit: "units",
    used: 412,
    usedPercent: 41.2,
    usedPriorMonth: 1280,
  },
  {
    allocation: null,
    allocationSource: "none",
    billing: "metered",
    connectionId: "conn_data",
    credentialSource: "own",
    enabled: true,
    features: [],
    primary: false,
    programmaticAllocation: null,
    projectedExhaustionAt: null,
    provider: "DataForSEO",
    providerId: "dataforseo",
    quotaReset: "none",
    remaining: null,
    requestCount: 1,
    unconfirmedCount: 0,
    state: "no_allocation",
    status: "connected",
    own: {
      requestCount: 1,
      surfaces: {
        app: {
          allocation: null,
          projectedExhaustionAt: null,
          remaining: null,
          state: "no_allocation",
          used: 10,
          usedPercent: null,
        },
        programmatic: {
          allocation: null,
          projectedExhaustionAt: null,
          remaining: null,
          state: "no_allocation",
          used: 0,
          usedPercent: null,
        },
      },
      unconfirmedCount: 0,
      unit: "cents",
      used: 10,
      usedPriorMonth: 40,
    },
    credits: {
      requestCount: 0,
      surfaces: {
        app: {
          allocation: null,
          projectedExhaustionAt: null,
          remaining: null,
          state: "no_allocation",
          used: 0,
          usedPercent: null,
        },
        programmatic: {
          allocation: null,
          projectedExhaustionAt: null,
          remaining: null,
          state: "no_allocation",
          used: 0,
          usedPercent: null,
        },
      },
      unconfirmedCount: 0,
      unit: "cents",
      used: 0,
      usedPriorMonth: 0,
    },
    surfaces: {
      app: {
        allocation: null,
        projectedExhaustionAt: null,
        remaining: null,
        state: "no_allocation",
        used: 10,
        usedPercent: null,
      },
      programmatic: {
        allocation: null,
        projectedExhaustionAt: null,
        remaining: null,
        state: "no_allocation",
        used: 0,
        usedPercent: null,
      },
    },
    unit: "cents",
    used: 10,
    usedPercent: null,
    usedPriorMonth: 40,
  },
] satisfies ProviderSpendConnection[];

export const dialogCopy =
  usageSettingsFeatureTestMessages.projectSettingsUsage.provider.budgetDialog;

export const surfaceLabel = (template: string, provider: string) =>
  template.replace("{provider}", provider);
