import type { RunPageInitialData, RunPageItem } from "./RunPageTypes";

function item(overrides: Partial<RunPageItem> & Pick<RunPageItem, "id" | "status">): RunPageItem {
  return {
    actualCostCents: 6,
    blockedReason: null,
    estimatedCostCents: 6,
    finishedAt: null,
    keyword: {
      device: "desktop",
      languageLabel: "English",
      location: "Spain",
      publicId: `kw_${overrides.id}`,
      text: "headless cms",
    },
    notBefore: null,
    rankCheck: { errorCode: null, position: 7, publicId: `chk_${overrides.id}`, rankingUrl: null },
    startedAt: null,
    ...overrides,
  };
}

export const runPageFixture: RunPageInitialData = {
  items: [
    item({
      finishedAt: "2026-08-31T14:22:00.000Z",
      id: "alpha",
      keyword: {
        device: "mobile",
        languageLabel: "Spanish",
        location: "Spain",
        publicId: "kw_alpha",
        text: "alpha cms",
      },
      status: "completed",
    }),
    item({
      id: "zeta",
      keyword: {
        device: "desktop",
        languageLabel: "English",
        location: "Belgium",
        publicId: "kw_zeta",
        text: "zeta cms",
      },
      startedAt: "2026-08-31T14:25:00.000Z",
      status: "running",
    }),
    item({
      blockedReason: "Paused target - resumes when you unpause it",
      id: "skipped-paused",
      keyword: {
        device: "desktop",
        languageLabel: "Spanish",
        location: "Spain",
        publicId: "kw_skipped_paused",
        text: "wordpress alternative",
      },
      rankCheck: null,
      status: "skipped",
    }),
    item({
      blockedReason: "Off-catalog pair - Arabic is not offered for Belgium",
      id: "skipped-market",
      keyword: {
        device: "mobile",
        languageLabel: "Arabic",
        location: "Belgium",
        publicId: "kw_skipped_market",
        text: "cms benchmarks",
      },
      rankCheck: null,
      status: "skipped",
    }),
  ],
  nextCursor: "cursor-next",
  now: "2026-08-31T14:24:12.000Z",
  run: {
    blockedReason: null,
    checkSchedulePublicId: "sch_example",
    costCents: 151,
    counts: {
      cancelled: 0,
      completed: 248,
      deferred: 0,
      failed: 4,
      requested: 350,
      skipped: 6,
      total: 694,
    },
    estimatedCostCents: 416,
    finishedAt: null,
    id: "rcr_9d2e41",
    keywordCount: 350,
    startedTargets: 253,
    hasRunningTargets: true,
    launchedAt: "2026-08-31T14:20:00.000Z",
    kind: "rank_check",
    outcome: null,
    parentRelation: null,
    parentRunId: null,
    parentRunPublicId: null,
    nextCheckAt: null,
    plannedFor: null,
    requestedBy: { name: "Anna Kowalska" },
    skippedBy: null,
    selectionKind: "filter",
    selectionSpec: { kind: "filter", v: 1 },
    startedAt: "2026-08-31T14:20:00.000Z",
    status: "running",
    targetCount: 700,
    trigger: "manual",
  },
};
