const eventKeyByAction = {
  "alert_rule.create": "alertRuleCreated",
  "alert_rule.set_enabled": "alertRuleAvailabilityChanged",
  "alert_rule.update": "alertRuleUpdated",
  "api_key.issue": "apiKeyCreated",
  "api_key.regenerate": "apiKeyRolled",
  "api_key.revoke": "apiKeyRevoked",
  "audit_log.view": "auditLogViewed",
  "auth.sign_in": "signedIn",
  "check_schedule.archive": "checkScheduleArchived",
  "check_schedule.assign": "checkScheduleAssigned",
  "check_schedule.create": "checkScheduleCreated",
  "check_schedule.delete": "checkScheduleDeleted",
  "check_schedule.remove": "checkScheduleRemoved",
  "check_schedule.restore": "checkScheduleRestored",
  "check_schedule.set_default": "checkScheduleDefaulted",
  "check_schedule.update": "checkScheduleUpdated",
  "cloud_import.cancel": "migrationCancelled",
  "cloud_import.export_package": "migrationPackageExported",
  "competitor.add": "competitorAdded",
  "competitor.remove": "competitorRemoved",
  "competitor.update": "competitorUpdated",
  "ingest_hook.create": "deployHookCreated",
  "ingest_hook.delete": "deployHookDeleted",
  "ingest_hook.disable": "deployHookDisabled",
  "ingest_hook.rotate": "deployHookRotated",
  "keyword.csv_export": "keywordExported",
  "keyword.csv_import": "keywordImported",
  "keyword_schedule.update": "keywordScheduleUpdated",
  "migration_token.mint": "migrationTokenCreated",
  "notification_preferences.update": "notificationPreferencesUpdated",
  "project.delete": "projectDeleted",
  "project.migration_hold.cancel": "migrationHoldCancelled",
  "project.migration_hold.enable": "migrationHoldEnabled",
  "project_defaults.update": "projectDefaultsUpdated",
  "provider.connect": "providerConnected",
  "provider.disconnect": "providerDisconnected",
  "provider.set_settings": "providerSettingsUpdated",
  "provider.test": "providerTested",
  "rank_check_run.skip": "scheduledRankCheckSkipped",
  "saved_view.create": "savedViewCreated",
  "saved_view.delete": "savedViewDeleted",
  "settings.budget_updated": "budgetUpdated",
  "settings.defaults.update": "projectDefaultsUpdated",
  "settings.experimental_modules.update": "experimentalModulesUpdated",
  "settings.presence_inspection_budget.update": "inspectionBudgetUpdated",
  "settings.project_details.update": "projectDetailsUpdated",
  "settings.project_domain.set": "projectDomainUpdated",
  "settings.project_domain.update": "projectDomainUpdated",
  "settings.project_tracking_scope.update": "trackingScopeUpdated",
  "settings.rank_check_frequency.update": "rankCheckFrequencyUpdated",
  "settings.search_data_sync.update": "searchDataSyncUpdated",
  "tag.create": "tagCreated",
  "tag.delete": "tagDeleted",
  "tag.rename": "tagRenamed",
  "team.invite.create": "memberInvited",
  "team.invite.revoke": "inviteRevoked",
  "team.member.remove": "memberRemoved",
  "team.ownership.transfer": "ownershipTransferred",
  "webhook_endpoint.create": "webhookCreated",
} as const;

export type AuditEventMessageKey = (typeof eventKeyByAction)[keyof typeof eventKeyByAction];

export function auditEventMessageKeyFor(action: string): AuditEventMessageKey | null {
  return eventKeyByAction[action as keyof typeof eventKeyByAction] ?? null;
}
