import type { SavedSiteAudit } from "@/lib/site-audit/schema";
export const auditFixture: SavedSiteAudit = {
  id: "agr_demo_audit",
  createdAt: "2026-10-02T10:00:00.000Z",
  cached: true,
  result: {
    version: 1,
    target: "https://acme.com/",
    startedAt: "2026-10-02T10:00:00.000Z",
    completedAt: "2026-10-02T10:00:02.000Z",
    state: "complete",
    stopReason: "finished",
    limits: { maxPages: 10, maxRequests: 20, maxDurationMs: 15000, maxPageBytes: 524288 },
    requests: 3,
    summary: { pages: 2, errors: 0, warnings: 2, indexable: 2 },
    limitations: [],
    pages: [
      {
        url: "https://acme.com/",
        finalUrl: "https://acme.com/",
        status: 200,
        responseTimeMs: 142,
        title: "Acme - keyword intelligence",
        description: "Monitor the keywords that matter to your business.",
        canonical: "https://acme.com/",
        headings: [{ level: 1, text: "Make your next move with better data" }],
        h1Count: 1,
        indexable: true,
        robots: null,
        internalLinkCount: 12,
        externalLinkCount: 3,
        internalLinks: ["https://acme.com/pricing"],
        imageCount: 4,
        missingAltCount: 0,
        issues: [],
      },
      {
        url: "https://acme.com/pricing",
        finalUrl: "https://acme.com/pricing",
        status: 200,
        responseTimeMs: 211,
        title: "Pricing - Acme",
        description: null,
        canonical: null,
        headings: [],
        h1Count: 0,
        indexable: true,
        robots: null,
        internalLinkCount: 8,
        externalLinkCount: 1,
        internalLinks: [],
        imageCount: 2,
        missingAltCount: 0,
        issues: [
          {
            code: "missing_description",
            severity: "warning",
            message: "Meta description is missing.",
          },
          { code: "h1_count", severity: "warning", message: "0 H1 headings; expected one." },
        ],
      },
    ],
  },
};
