import { oidcScopes } from "@/lib/auth/oidc-scopes";
import { absoluteUrl } from "./origin";

export function createAuthorizationServerMetadata(origin: string) {
  return {
    issuer: origin,
    authorization_endpoint: absoluteUrl(origin, "/api/auth/oauth2/authorize"),
    token_endpoint: absoluteUrl(origin, "/api/auth/oauth2/token"),
    userinfo_endpoint: absoluteUrl(origin, "/api/auth/oauth2/userinfo"),
    jwks_uri: absoluteUrl(origin, "/api/auth/jwks"),
    registration_endpoint: absoluteUrl(origin, "/api/auth/oauth2/register"),
    end_session_endpoint: absoluteUrl(origin, "/api/auth/oauth2/endsession"),
    response_types_supported: ["code"],
    response_modes_supported: ["query"],
    grant_types_supported: ["authorization_code", "refresh_token"],
    code_challenge_methods_supported: ["S256"],
    subject_types_supported: ["public"],
    id_token_signing_alg_values_supported: ["EdDSA"],
    token_endpoint_auth_methods_supported: ["none", "client_secret_basic", "client_secret_post"],
    scopes_supported: oidcScopes,
    claims_supported: [
      "sub",
      "iss",
      "aud",
      "exp",
      "nbf",
      "iat",
      "jti",
      "email",
      "email_verified",
      "name",
    ],
    agent_auth: {
      skill: absoluteUrl(origin, "/auth.md"),
      register_uri: absoluteUrl(origin, "/api/auth/oauth2/register"),
      registration: ["dynamic_client_registration"],
      identity_types_supported: ["anonymous"],
      anonymous: {
        credential_types_supported: ["oauth2_client"],
        claim_uri: absoluteUrl(origin, "/login"),
      },
      claim_uri: absoluteUrl(origin, "/login"),
    },
  };
}

export function createOAuthProtectedResource(origin: string) {
  return {
    authorization_servers: [origin],
    bearer_methods_supported: ["header"],
    resource: absoluteUrl(origin, "/api/v1"),
    scopes_supported: ["read", "write", "admin"],
  };
}

export function createAuthMarkdown(origin: string) {
  return [
    "# Bisibility auth.md",
    "",
    "Bisibility supports agent access through personal access tokens (PATs)",
    "and project API keys.",
    "",
    "## Audience",
    "",
    "Agents, MCP clients, scripts, and integrations that need to read or update",
    "rank-tracking data through the Bisibility REST API.",
    "",
    "## Choose a credential",
    "",
    "- Personal access token (`bsb_pat_live_`): use for user, cross-project, or",
    "  account-level automation. Create it in Account -> Security.",
    "- Project API key (`bsb_key_live_`): use for an integration isolated to one",
    "  project. Create it in Project Settings -> API keys.",
    "",
    "Choose the minimum permission level the agent needs: `read`, `write`, or",
    "`admin`. Store the raw credential securely; it is shown only once.",
    "",
    "## CLI browser sign-in",
    "",
    "The `bisibility auth login` command uses OAuth 2.1 Authorization Code with",
    "PKCE S256. It opens a browser so the user can sign in and approve access.",
    "",
    "After authorization, the CLI receives a short-lived OAuth access token with",
    "the `tokens:write` scope and exchanges it at `POST /api/v1/me/tokens` for a",
    "PAT. The stored API credential is the PAT.",
    "",
    "An OAuth access token is not a direct REST API credential. REST clients use",
    "the resulting PAT or a project API key.",
    "",
    "## Credential use",
    "",
    "Send the PAT or project API key on every API call:",
    "",
    "```http",
    "Authorization: Bearer <token>",
    "```",
    "",
    "Credentials are hashed at rest. Revoke and recreate a credential if it",
    "leaks. Rate limits are enforced per credential; 429 responses include the",
    "retry window.",
    "",
    "## Discovery metadata",
    "",
    `- OAuth protected resource metadata: ${absoluteUrl(
      origin,
      "/.well-known/oauth-protected-resource",
    )}`,
    `- OAuth authorization server metadata: ${absoluteUrl(
      origin,
      "/.well-known/oauth-authorization-server",
    )}`,
    `- OpenID Connect metadata: ${absoluteUrl(origin, "/.well-known/openid-configuration")}`,
    `- Authorization endpoint: ${absoluteUrl(origin, "/api/auth/oauth2/authorize")}`,
    `- Token endpoint: ${absoluteUrl(origin, "/api/auth/oauth2/token")}`,
    `- Userinfo endpoint: ${absoluteUrl(origin, "/api/auth/oauth2/userinfo")}`,
    `- Dynamic client registration: ${absoluteUrl(origin, "/api/auth/oauth2/register")}`,
    `- Agent Skills index: ${absoluteUrl(origin, "/.well-known/agent-skills/index.json")}`,
    `- MCP server card: ${absoluteUrl(origin, "/.well-known/mcp/server-card.json")}`,
    "",
    "The OAuth server supports `openid`, `profile`, `email`, `offline_access`,",
    "and `tokens:write` scopes. Dynamic clients receive `oauth2_client`",
    "credentials and use the browser consent flow.",
    "",
    "## Useful API links",
    "",
    `- OpenAPI: ${absoluteUrl(origin, "/api/v1/openapi.json")}`,
    `- Capabilities: ${absoluteUrl(origin, "/api/v1/capabilities")}`,
    `- Health: ${absoluteUrl(origin, "/api/v1/health")}`,
    `- Authentication docs: ${absoluteUrl(origin, "/docs/authentication")}`,
    `- Personal access token docs: ${absoluteUrl(origin, "/docs/api/personal-access-tokens")}`,
    `- API key docs: ${absoluteUrl(origin, "/docs/api/api-keys")}`,
  ].join("\n");
}
