export const TWO_FACTOR_FRESH_SESSION_SECONDS = 5 * 60;
export const TWO_FACTOR_STEP_UP_ATTEMPT_LIMIT = 5;
export const TWO_FACTOR_STEP_UP_WINDOW_SECONDS = 5 * 60;
export const TWO_FACTOR_STEP_UP_LOCK_SECONDS = 15 * 60;
export const TWO_FACTOR_STEP_UP_GRANT_SECONDS = 2 * 60;
